-- =============================================
-- Seed data — Demo content for all modules
-- Run AFTER running 001_initial_schema.sql
-- =============================================

-- NOTE: Create an admin user first via Supabase Auth dashboard,
-- then update their profile role to 'admin':
-- UPDATE public.profiles SET role = 'admin' WHERE id = 'your-user-uuid';

-- Hero Sliders
INSERT INTO public.hero_sliders (image_url, title, description, button_text, button_link, sort_order, is_active)
VALUES
  ('https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1920&q=80', 'Welcome to WebMarket', 'Your trusted partner for quality products and professional services.', 'Explore Services', '/services', 1, true),
  ('https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=1920&q=80', 'Quality Products You Can Trust', 'Browse our extensive catalog of premium products designed for your needs.', 'View Products', '/products', 2, true),
  ('https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1920&q=80', 'Get In Touch With Us', 'We are here to help you find the perfect solution for your business.', 'Contact Us', '/contact', 3, true);

-- About Page
INSERT INTO public.pages (slug, title, banner_image, content, meta_title, meta_description)
VALUES (
  'about',
  'About Us',
  'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1920&q=80',
  '{
    "description": "WebMarket was founded with a simple mission: to deliver exceptional quality products and services to businesses and individuals across the region. For over a decade, we have been a trusted name in the industry, built on the pillars of integrity, innovation, and customer satisfaction.\n\nOur team of dedicated professionals brings together decades of combined experience to ensure that every client receives personalized attention and solutions tailored to their specific needs.",
    "vision_title": "Our Vision",
    "vision_description": "To be the most trusted and innovative provider of products and services, empowering businesses to thrive in a competitive marketplace through quality, reliability, and exceptional customer experiences.",
    "mission_title": "Our Mission",
    "mission_description": "We strive to deliver superior quality products and services that exceed customer expectations, foster long-term partnerships built on trust, and continuously innovate to stay ahead of industry trends — all while maintaining the highest standards of business ethics."
  }',
  'About Us — WebMarket',
  'Learn about WebMarket, our vision, mission, and the dedicated team behind our success.'
) ON CONFLICT (slug) DO NOTHING;

-- Services
INSERT INTO public.services (slug, title, description, content, image_url, sort_order, is_published)
VALUES
  ('consulting', 'Business Consulting', 'Expert guidance to help your business grow and succeed in today''s competitive market.', '<p>Our business consulting services are designed to provide you with strategic insights and actionable plans that drive real results. Our team of experienced consultants works closely with you to understand your unique challenges and opportunities.</p><h2>What We Offer</h2><ul><li>Strategic planning and roadmap development</li><li>Market analysis and competitive intelligence</li><li>Operational efficiency optimization</li><li>Change management support</li><li>Performance metrics and KPI tracking</li></ul>', 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&q=80', 1, true),
  ('digital-marketing', 'Digital Marketing', 'Comprehensive digital marketing strategies to boost your online presence and drive conversions.', '<p>In the digital age, having a strong online presence is crucial for business success. Our digital marketing team creates data-driven campaigns that reach your target audience at the right time with the right message.</p><h2>Our Services Include</h2><ul><li>Search Engine Optimization (SEO)</li><li>Pay-Per-Click (PPC) advertising</li><li>Social media marketing and management</li><li>Content marketing and strategy</li><li>Email marketing campaigns</li><li>Analytics and reporting</li></ul>', 'https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?w=800&q=80', 2, true),
  ('web-development', 'Web Development', 'Custom web solutions from responsive websites to complex web applications built for performance.', '<p>We build beautiful, high-performance websites and web applications that not only look great but also deliver exceptional user experiences. Our development team uses the latest technologies and best practices to ensure your web presence stands out.</p><h2>Technologies We Use</h2><ul><li>Next.js and React for modern frontends</li><li>Node.js and Python for robust backends</li><li>PostgreSQL and MongoDB for databases</li><li>AWS and Vercel for cloud deployment</li><li>Tailwind CSS for responsive design</li></ul>', 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&q=80', 3, true),
  ('it-support', 'IT Support & Maintenance', 'Reliable IT support services to keep your systems running smoothly around the clock.', '<p>Technology should work for you, not against you. Our IT support and maintenance services ensure your systems are always up and running at peak performance, so you can focus on what matters most — your business.</p><h2>Support Services</h2><ul><li>24/7 help desk support</li><li>Network setup and management</li><li>Server administration</li><li>Security audits and implementation</li><li>Backup and disaster recovery</li><li>Software updates and patch management</li></ul>', 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80', 4, true),
  ('cloud-solutions', 'Cloud Solutions', 'Migrate to the cloud and unlock scalability, flexibility, and cost savings for your business.', '<p>Cloud computing has transformed how businesses operate, offering unprecedented flexibility and scalability. Our cloud solutions help you migrate to and manage cloud infrastructure efficiently, ensuring a smooth transition with minimal disruption to your operations.</p><h2>Cloud Services</h2><ul><li>Cloud migration strategy and execution</li><li>Multi-cloud and hybrid cloud setups</li><li>Cloud security and compliance</li><li>Cost optimization and monitoring</li><li>DevOps and CI/CD implementation</li></ul>', 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80', 5, true),
  ('data-analytics', 'Data Analytics', 'Transform your raw data into meaningful insights that drive smarter business decisions.', '<p>Data is the new currency of business. Our data analytics services help you collect, process, and analyze your data to uncover valuable insights that give you a competitive edge and help you make more informed decisions.</p><h2>Analytics Capabilities</h2><ul><li>Business intelligence dashboards</li><li>Predictive analytics and forecasting</li><li>Data warehouse design and management</li><li>Real-time analytics pipelines</li><li>Custom reporting and visualization</li></ul>', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80', 6, true);

-- Products
INSERT INTO public.products (slug, title, description, content, image_url, sort_order, is_published)
VALUES
  ('enterprise-suite', 'Enterprise Suite', 'Complete business management solution designed for large organizations with complex needs.', '<p>The Enterprise Suite is our flagship product, designed to handle the complex needs of large organizations. It includes everything you need to manage your business operations efficiently and effectively.</p><h2>Key Features</h2><ul><li>Advanced CRM with pipeline management</li><li>Integrated ERP modules</li><li>Real-time analytics dashboard</li><li>Multi-user access with role management</li><li>API integrations with 200+ tools</li><li>24/7 premium support</li></ul>', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80', 1, true),
  ('business-pro', 'Business Pro', 'The perfect solution for growing businesses ready to scale their operations.', '<p>Business Pro is built for ambitious companies looking to streamline their operations and scale efficiently. With powerful automation features and intuitive interfaces, your team will be more productive than ever.</p><h2>Highlights</h2><ul><li>Project and task management</li><li>Team collaboration tools</li><li>Financial reporting and invoicing</li><li>Customer management</li><li>50+ integrations</li></ul>', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80', 2, true),
  ('starter-pack', 'Starter Pack', 'Everything a small business needs to get started and grow in the digital age.', '<p>The Starter Pack gives small businesses everything they need to compete in today''s digital marketplace. Simple, affordable, and powerful — it''s the perfect foundation for your business growth.</p><h2>Includes</h2><ul><li>Website and e-commerce setup</li><li>Basic CRM</li><li>Email marketing tools</li><li>Social media management</li><li>Basic analytics</li></ul>', 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80', 3, true),
  ('analytics-platform', 'Analytics Platform', 'Deep insights and real-time analytics to power data-driven decision making.', '<p>Our Analytics Platform transforms raw data into actionable insights. With real-time dashboards, custom reports, and predictive analytics, you''ll always have the information you need to stay ahead.</p><h2>Features</h2><ul><li>Real-time data processing</li><li>Customizable dashboards</li><li>Automated reporting</li><li>AI-powered predictions</li><li>Data export and API access</li></ul>', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80', 4, true),
  ('security-shield', 'Security Shield', 'Enterprise-grade cybersecurity solution to protect your business from threats.', '<p>Protect your business from evolving cyber threats with Security Shield. Our comprehensive security solution monitors, detects, and responds to threats in real time, keeping your data and systems safe.</p><h2>Protection Features</h2><ul><li>Threat detection and response</li><li>DDoS protection</li><li>SSL and encryption management</li><li>Compliance tools (GDPR, HIPAA)</li><li>Security audit reports</li></ul>', 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&q=80', 5, true),
  ('cloud-backup', 'Cloud Backup Pro', 'Automated, encrypted backup solution ensuring your data is always safe and recoverable.', '<p>Never lose critical data again with Cloud Backup Pro. Our automated solution backs up your data continuously, encrypts it for security, and stores it in geographically distributed data centers.</p><h2>Backup Features</h2><ul><li>Continuous real-time backup</li><li>AES-256 encryption</li><li>Geo-redundant storage</li><li>One-click restoration</li><li>99.99% uptime SLA</li></ul>', 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=800&q=80', 6, true);

-- Gallery
INSERT INTO public.gallery (image_url, caption, sort_order, is_active)
VALUES
  ('https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80', 'Our Modern Office Space', 1, true),
  ('https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80', 'Team Collaboration Session', 2, true),
  ('https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&q=80', 'Product Development Lab', 3, true),
  ('https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', 'Technology Showcase', 4, true),
  ('https://images.unsplash.com/photo-1542744094-3a31f272c490?w=800&q=80', 'Client Presentation', 5, true),
  ('https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&q=80', 'Customer Support Team', 6, true),
  ('https://images.unsplash.com/photo-1576267423445-b2e0074d68a4?w=800&q=80', 'Annual Company Event', 7, true),
  ('https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&q=80', 'Executive Meeting Room', 8, true),
  ('https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80', 'Product Demo Session', 9, true);

-- Blogs
INSERT INTO public.blogs (slug, title, excerpt, content, cover_image, author, published_at, meta_title, meta_description, is_published)
VALUES
  ('future-of-digital-transformation', 'The Future of Digital Transformation in 2024', 'Explore how digital transformation is reshaping industries and what businesses need to do to stay competitive in an increasingly digital world.', '<p>Digital transformation is no longer a buzzword — it''s a business imperative. As we progress through 2024, organizations across every industry are accelerating their digital journeys, driven by changing customer expectations, competitive pressures, and the promise of greater efficiency and innovation.</p><h2>Key Trends Shaping Digital Transformation</h2><p>Several major trends are defining the digital transformation landscape this year:</p><h3>1. AI and Machine Learning at Scale</h3><p>Artificial intelligence is moving from experimental to operational. Businesses are deploying AI across customer service, operations, and product development, with 70% of enterprises expected to have implemented AI by end of 2024.</p><h3>2. Cloud-First Strategies</h3><p>The cloud has become the default deployment model for new applications. Multi-cloud and hybrid cloud strategies are gaining traction as organizations seek flexibility and avoid vendor lock-in.</p><h3>3. Data-Driven Decision Making</h3><p>Real-time analytics and business intelligence tools are making it possible for companies to make faster, more informed decisions based on data rather than intuition.</p><h2>What This Means for Your Business</h2><p>If you haven''t already begun your digital transformation journey, the time to start is now. The gap between digital leaders and laggards is widening, and catching up becomes harder with each passing year.</p><p>Start small, focus on high-impact areas, and build momentum through quick wins. The goal is not to transform overnight but to establish a culture of continuous improvement and digital innovation.</p>', 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&q=80', 'WebMarket Editorial Team', now() - interval '5 days', 'The Future of Digital Transformation | WebMarket Blog', 'Explore how digital transformation trends in 2024 are reshaping business and what you need to know to stay ahead.', true),
  ('cybersecurity-best-practices', '10 Cybersecurity Best Practices Every Business Needs', 'Cyber threats are evolving rapidly. Here are the essential security practices that every business should implement to protect their digital assets.', '<p>Cyber attacks are becoming more sophisticated and frequent. In 2024, the average cost of a data breach reached new highs, making cybersecurity not just an IT concern but a critical business priority. Here are 10 best practices every business should implement:</p><h2>1. Implement Multi-Factor Authentication (MFA)</h2><p>MFA adds an extra layer of security by requiring users to verify their identity through multiple methods. Enable MFA for all accounts, especially those with access to sensitive data.</p><h2>2. Keep Software Updated</h2><p>Outdated software is one of the most common entry points for cyber attacks. Establish a regular patch management process to ensure all systems are up to date.</p><h2>3. Train Your Employees</h2><p>Human error is a leading cause of security breaches. Regular security awareness training helps employees recognize phishing attempts, social engineering, and other threats.</p><h2>4. Use Strong Password Policies</h2><p>Enforce strong, unique passwords for all accounts and use a password manager to help employees manage them securely.</p><h2>5. Encrypt Sensitive Data</h2><p>Ensure all sensitive data, both in transit and at rest, is encrypted using industry-standard encryption algorithms.</p><h2>6. Regular Security Audits</h2><p>Conduct regular security assessments and penetration testing to identify vulnerabilities before attackers do.</p><h2>7. Implement Least Privilege Access</h2><p>Give users only the access they need to do their jobs. This limits the damage that can be done if an account is compromised.</p><h2>8. Have an Incident Response Plan</h2><p>Prepare for the inevitable. Have a documented plan for how your organization will respond to a security incident.</p><h2>9. Back Up Your Data</h2><p>Regular, encrypted backups stored offsite can be the difference between a minor inconvenience and a catastrophic loss after a ransomware attack.</p><h2>10. Monitor Your Networks</h2><p>Implement continuous monitoring and logging to detect and respond to threats in real time.</p>', 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1200&q=80', 'Security Team', now() - interval '12 days', '10 Cybersecurity Best Practices | WebMarket Blog', 'Learn the 10 essential cybersecurity practices every business must implement to protect against modern threats.', true),
  ('cloud-migration-guide', 'Complete Guide to Cloud Migration for Small Businesses', 'Moving to the cloud can seem daunting, but with the right approach, it can transform your business. Here''s your step-by-step guide.', '<p>Cloud migration can feel overwhelming for small businesses, but the benefits far outweigh the challenges. From cost savings to improved scalability, the cloud offers opportunities that were once only available to large enterprises.</p><h2>Why Migrate to the Cloud?</h2><p>Before diving into how, let''s understand why cloud migration makes sense for small businesses:</p><ul><li><strong>Cost Efficiency</strong>: Pay only for what you use, eliminating large upfront infrastructure investments</li><li><strong>Scalability</strong>: Scale up or down instantly based on your business needs</li><li><strong>Reliability</strong>: Cloud providers offer 99.9%+ uptime with built-in disaster recovery</li><li><strong>Collaboration</strong>: Enable your team to work from anywhere, on any device</li><li><strong>Security</strong>: Benefit from enterprise-grade security managed by cloud providers</li></ul><h2>Step 1: Assess Your Current Infrastructure</h2><p>Start by taking inventory of all your applications, data, and infrastructure. Categorize each item by complexity and priority for migration.</p><h2>Step 2: Choose Your Cloud Strategy</h2><p>Consider which approach works best for your situation: lift-and-shift, re-platforming, or refactoring. For most small businesses, lift-and-shift is the fastest path to the cloud.</p><h2>Step 3: Select Your Cloud Provider</h2><p>AWS, Google Cloud, and Azure are the major providers. For small businesses, starting with one provider simplifies management and support.</p><h2>Step 4: Plan Your Migration</h2><p>Create a detailed migration plan with timelines, responsible parties, and rollback procedures. Start with less critical workloads to build confidence.</p><h2>Step 5: Execute and Optimize</h2><p>Begin migrating in phases. After each phase, optimize your cloud resources to ensure cost efficiency and performance.</p>', 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=1200&q=80', 'Cloud Solutions Team', now() - interval '20 days', 'Complete Cloud Migration Guide for Small Businesses | WebMarket', 'A comprehensive step-by-step guide to help small businesses successfully migrate to the cloud.', true);

-- Testimonials
INSERT INTO public.testimonials (name, designation, message, photo_url, sort_order, is_active)
VALUES
  ('Sarah Johnson', 'CEO, TechStart Inc.', 'WebMarket transformed our digital presence completely. Their team is professional, responsive, and delivered beyond our expectations. Our online sales increased by 45% in the first quarter after launch.', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80', 1, true),
  ('Michael Chen', 'CTO, DataFlow Systems', 'The cloud migration solution they provided was seamless and efficient. We experienced zero downtime during the transition, which is remarkable. Their technical expertise is top-notch.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80', 2, true),
  ('Emily Rodriguez', 'Marketing Director, GrowthCo', 'The digital marketing strategy they developed for us has been a game-changer. We''ve seen a 3x increase in qualified leads and our cost per acquisition has dropped significantly.', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&q=80', 3, true),
  ('David Kim', 'Operations Manager, LogiTech', 'Their Enterprise Suite has streamlined our entire operation. The ROI has been incredible — we''ve saved over 20 hours per week in manual processes alone. Highly recommend!', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80', 4, true),
  ('Amanda Wilson', 'Founder, Creative Studio', 'Working with WebMarket felt like having a partner who genuinely cared about our success. They went above and beyond to ensure everything was perfect. Five stars, without hesitation.', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80', 5, true),
  ('Robert Patel', 'CFO, Financial Solutions Ltd.', 'The security audit they performed uncovered several vulnerabilities we weren''t aware of. Their remediation plan was clear and thorough. We now have peace of mind knowing our data is secure.', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80', 6, true);
